import * as vscode from 'vscode'
import { checkTool, runTool } from './toolDiscovery'

function buildEnvironmentReport(): string {
  const lines: string[] = []
  const now = new Date().toISOString()

  // --- OS ---
  const platform = process.platform
  const osName = platform === 'win32' ? 'Windows' : platform === 'darwin' ? 'macOS' : 'Linux'
  const arch = process.arch

  // --- Python ---
  const py3 = runTool('python3', ['--version']) || runTool('python', ['--version'])
  const pyCmd = checkTool('python3', ['--version'])
    ? 'python3'
    : checkTool('python', ['--version']) ? 'python' : ''
  const hasPy = pyCmd !== ''

  // --- PDF libraries ---
  const hasFitz = hasPy && checkTool(pyCmd, ['-c', 'import fitz; print("ok")'])
  const fitzVer = hasFitz
    ? runTool(pyCmd, ['-c', 'import fitz; print(fitz.__version__)'])
    : ''
  const hasPlumber = hasPy && checkTool(
    pyCmd,
    ['-c', 'import pdfplumber; print("ok")']
  )
  const hasPdfminer = hasPy && checkTool(
    pyCmd,
    ['-c', 'import pdfminer; print("ok")']
  )

  // --- Image libraries ---
  const hasPillow = hasPy && checkTool(
    pyCmd,
    ['-c', 'from PIL import Image; print("ok")']
  )
  const pillowVer = hasPillow
    ? runTool(pyCmd, ['-c', 'from PIL import __version__; print(__version__)'])
    : ''
  const hasCV2 = hasPy && checkTool(pyCmd, ['-c', 'import cv2; print("ok")'])

  // --- CLI tools ---
  const hasPdftotext = checkTool('pdftotext', ['-v']) ||
    checkTool('pdftotext', ['--help'])
  const hasConvert = checkTool('convert', ['--version'])
  const hasMagick = checkTool('magick', ['--version'])
  const hasGhostscript = checkTool('gs', ['--version']) ||
    checkTool('gswin64c', ['--version'])

  const ok = (v: boolean | string) => v ? '✅' : '❌'

  lines.push(`# NodeGraph — Agent Environment Report`)
  lines.push(``)
  lines.push(`> Auto-generated by the NodeGraph extension at activation.`)
  lines.push(`> **AI agents: read this file to understand what tools are available on this machine.**`)
  lines.push(`> Re-generated each time a \`.nodegraph.json\` file is opened.`)
  lines.push(``)
  lines.push(`Generated: \`${now}\``)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)
  lines.push(`## System`)
  lines.push(``)
  lines.push(`| | |`)
  lines.push(`|---|---|`)
  lines.push(`| OS | ${osName} (\`${platform}\`) |`)
  lines.push(`| Architecture | \`${arch}\` |`)
  lines.push(`| Python | ${hasPy ? `${ok(true)} \`${py3}\`` : `${ok(false)} not found`} |`)
  lines.push(`| Python command | ${hasPy ? `\`${pyCmd}\`` : 'N/A'} |`)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)
  lines.push(`## PDF Reading Capabilities`)
  lines.push(``)
  lines.push(`| Tool | Available | Notes |`)
  lines.push(`|------|:---------:|-------|`)
  lines.push(`| PyMuPDF (\`fitz\`) | ${ok(hasFitz)} | ${hasFitz ? `v${fitzVer} — recommended` : 'Install: \`pip install pymupdf\`'} |`)
  lines.push(`| pdfplumber | ${ok(hasPlumber)} | ${hasPlumber ? 'available' : 'Install: \`pip install pdfplumber\`'} |`)
  lines.push(`| pdfminer | ${ok(hasPdfminer)} | ${hasPdfminer ? 'available' : 'Install: \`pip install pdfminer.six\`'} |`)
  lines.push(`| poppler (\`pdftotext\`) | ${ok(hasPdftotext)} | ${hasPdftotext ? 'CLI tool available' : platform === 'win32' ? 'Install: download poppler for Windows' : platform === 'darwin' ? 'Install: \`brew install poppler\`' : 'Install: \`apt install poppler-utils\`'} |`)
  lines.push(`| Ghostscript (\`gs\`) | ${ok(hasGhostscript)} | ${hasGhostscript ? 'available' : 'optional'} |`)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)
  lines.push(`## Image Processing Capabilities`)
  lines.push(``)
  lines.push(`| Tool | Available | Notes |`)
  lines.push(`|------|:---------:|-------|`)
  lines.push(`| Pillow (\`PIL\`) | ${ok(hasPillow)} | ${hasPillow ? `v${pillowVer} — recommended` : 'Install: \`pip install Pillow\`'} |`)
  lines.push(`| OpenCV (\`cv2\`) | ${ok(hasCV2)} | ${hasCV2 ? 'available' : 'Install: \`pip install opencv-python\`'} |`)
  lines.push(`| ImageMagick (\`convert\`) | ${ok(hasConvert || hasMagick)} | ${(hasConvert || hasMagick) ? 'CLI tool available' : platform === 'win32' ? 'Install: imagemagick.org' : platform === 'darwin' ? 'Install: \`brew install imagemagick\`' : 'Install: \`apt install imagemagick\`'} |`)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)
  lines.push(`## Agent Recommendations`)
  lines.push(``)

  if (!hasPy) {
    lines.push(`> ⚠️ **Python not found.** PDF reading and image processing via Python are not available.`)
    lines.push(`> Install Python from https://python.org, then reopen a \`.nodegraph.json\` file to re-run this check.`)
    lines.push(``)
  }

  lines.push(`### Reading a PDF`)
  if (hasFitz) {
    lines.push(`Use PyMuPDF (recommended — fastest and most accurate):`)
    lines.push(`\`\`\`python`)
    lines.push(`import fitz`)
    lines.push(`doc = fitz.open("paper.pdf")`)
    lines.push(`text = "\\n".join(page.get_text() for page in doc)`)
    lines.push(`\`\`\``)
  } else if (hasPlumber) {
    lines.push(`Use pdfplumber:`)
    lines.push(`\`\`\`python`)
    lines.push(`import pdfplumber`)
    lines.push(`with pdfplumber.open("paper.pdf") as pdf:`)
    lines.push(`    text = "\\n".join(p.extract_text() or "" for p in pdf.pages)`)
    lines.push(`\`\`\``)
  } else if (hasPdftotext) {
    lines.push(`Use poppler CLI:`)
    lines.push(`\`\`\`bash`)
    lines.push(`pdftotext paper.pdf -`)
    lines.push(`\`\`\``)
  } else {
    lines.push(`❌ No PDF reading tool available. Ask the user to install PyMuPDF: \`pip install pymupdf\``)
  }

  lines.push(``)
  lines.push(`### Extracting images from a PDF`)
  if (hasFitz) {
    lines.push(`\`\`\`python`)
    lines.push(`import fitz`)
    lines.push(`doc = fitz.open("paper.pdf")`)
    lines.push(`for i, page in enumerate(doc):`)
    lines.push(`    for img in page.get_images():`)
    lines.push(`        xref = img[0]`)
    lines.push(`        pix = fitz.Pixmap(doc, xref)`)
    lines.push(`        pix.save(f"fig_{i}_{xref}.png")`)
    lines.push(`\`\`\``)
  } else if (hasPillow) {
    lines.push(`Pillow is available but cannot extract from PDF directly. Use PyMuPDF for extraction.`)
  } else {
    lines.push(`❌ No image extraction tool available.`)
  }

  lines.push(``)
  lines.push(`---`)
  lines.push(``)
  lines.push(`*To refresh this report, reopen any \`.nodegraph.json\` file.*`)

  return lines.join('\n')
}

// Writes ENVIRONMENT.md into one specific folder. Used both by the
// per-workspace-folder loop below (activation time) and by the
// "Copy Agent Spec to Workspace" command (extension.ts), which needs it
// written into the exact folder it targets — not necessarily a workspace
// root — so that folder ends up with both agent files together, consistent
// with what NODEGRAPH_SPEC.md expects to find next to it.
export async function writeEnvironmentReportToFolder(folderUri: vscode.Uri): Promise<boolean> {
  const agentDir = vscode.Uri.joinPath(folderUri, '.agent')
  const outFile = vscode.Uri.joinPath(agentDir, 'ENVIRONMENT.md')
  try {
    await vscode.workspace.fs.createDirectory(agentDir)
    await vscode.workspace.fs.writeFile(outFile, Buffer.from(buildEnvironmentReport(), 'utf-8'))
    return true
  } catch {
    return false
  }
}

export async function writeEnvironmentReport(workspaceFolders: readonly vscode.WorkspaceFolder[]): Promise<void> {
  if (!workspaceFolders || workspaceFolders.length === 0) return
  for (const folder of workspaceFolders) {
    await writeEnvironmentReportToFolder(folder.uri)
  }
}

// NODEGRAPH_SPEC.md ships inside the extension bundle, not the user's workspace,
// so an AI agent operating on the workspace has no way to find it without being
// told the extension's install path. Unlike ENVIRONMENT.md (small, genuinely
// per-machine, fine to regenerate silently every activation), this is a large
// static doc identical across every install — copying it into every workspace
// folder automatically would mean it can land in repos the user never chose to
// touch. So this only runs when the user explicitly invokes the "NodeGraph:
// Copy Agent Spec to Workspace" command, targeting exactly one folder — the one
// resolved by resolveTargetFolder() in extension.ts (Explorer right-click target,
// or a folder picker in a multi-root workspace).
export async function syncAgentSpec(extensionUri: vscode.Uri, targetFolder: vscode.Uri): Promise<boolean> {
  const bundledSpec = vscode.Uri.joinPath(extensionUri, '.agent', 'NODEGRAPH_SPEC.md')
  let content: Uint8Array
  try {
    content = await vscode.workspace.fs.readFile(bundledSpec)
  } catch {
    return false
  }

  const agentDir = vscode.Uri.joinPath(targetFolder, '.agent')
  const outFile = vscode.Uri.joinPath(agentDir, 'NODEGRAPH_SPEC.md')
  try {
    await vscode.workspace.fs.createDirectory(agentDir)
    await vscode.workspace.fs.writeFile(outFile, content)
    return true
  } catch {
    return false
  }
}

// Same idea as syncAgentSpec, for the ready-to-paste example prompts
// (README's "Example prompt" section) instead of the schema doc — copied
// from the extension bundle's .prompt/ folder into the target workspace
// folder's own .prompt/, so a user (or an agent acting for them) can open
// korean.md / english.md directly instead of copy-pasting out of the README.
export async function syncPromptTemplates(extensionUri: vscode.Uri, targetFolder: vscode.Uri): Promise<boolean> {
  const bundledDir = vscode.Uri.joinPath(extensionUri, '.prompt')
  const outDir = vscode.Uri.joinPath(targetFolder, '.prompt')
  try {
    await vscode.workspace.fs.createDirectory(outDir)
    for (const name of ['korean.md', 'english.md']) {
      const content = await vscode.workspace.fs.readFile(vscode.Uri.joinPath(bundledDir, name))
      await vscode.workspace.fs.writeFile(vscode.Uri.joinPath(outDir, name), content)
    }
    return true
  } catch {
    return false
  }
}
